# Use custom format

# Don't print a new line at the start of the prompt
add_newline = false

format = """
($character) $fill ($cmd_duration)

($directory) ($git_branch)($git_commit)($git_status)($git_metrics) ($username)(bold white)($hostname)($memory_usage)
($shlvl)($sudo)âœ  
"""

right_format = """$all"""

[fill]
symbol = "-"

# Replace the "â¯" symbol in the prompt with "âœ"
[character]
success_symbol = "[âœ“](bold green)"
error_symbol = "[âœ—](bold red)"

[directory]
#read_only = " ï€£"
format = "[$path]($style)[ $read_only]($read_only_style)"
truncation_symbol = "../"
#repo_root_style = "(bold green)"

[username]
#show_always = true
format = "[$user]($style)"

[hostname]
ssh_only = false
format = "@[$hostname](bold red) "
trim_at = "."
disabled = false

# [env_var.SHELL]
# variable = "SHELL"
# default = "unknown shell"
# [env_var.USER]
# default = "unknown user"

[cmd_duration]
format = "[ğŸ•‘ $duration]($style)"
min_time = 100
#show_milliseconds = true

[shlvl]
disabled = false
format = "[$symbol $shlvl ]($style)"
symbol = "â"
threshold = 2

#[jobs]
#disabled = true

# Disable the package module, hiding it from the prompt completely
[package]
display_private = true
format = "[$symbol$version ]($style)"

# Don't separate the prompt into two lines
[line_break]
#disabled = false

# Don't show battery charge
[battery]
disabled = false
full_symbol = "ï•¸"
charging_symbol = "ï–ƒ"
discharging_symbol = "ï–‚"

[dart]
symbol = "î˜ "

[git_branch]
#format = "@ [$symbol$branch]($style) "
format = "[$symbol](red) [$branch(:$remote_branch)]($style) "
symbol = "ï˜"

[git_metrics]
disabled = false

[memory_usage]
symbol = "ï¡š "
disabled = false
threshold = -1
#style = "bold dimmed green"
format = " [$symbol${ram_pct}]($style) "

[nix_shell]
symbol = "ï‹œ "

[nodejs]
#symbol = "î‰ "
format = "$symbol($style)"
style = "bold green"

[php]
symbol = "î˜ˆ "

[python]
python_binary = "python3"
style = "green bold"
symbol = "î˜† "

[ruby]
symbol = "îˆ¾ "

[rust]
symbol = "ï€“ "

#[shell]
#fish_indicator = "ïœ¹"
#powershell_indicator = "ï‘ _"
#unknown_indicator = "mystery shell"
#style = "cyan bold"
#disabled = false

#[status]
#style = "bg:blue"
#symbol = "ğŸ”´ "
#success_symbol = "ğŸŸ¢ SUCCESS"
#format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
#map_symbol = true
#disabled = false

[sudo]
symbol = "ğŸš€ "
disabled = false
format = "[$symbol]($style)"